language: php

dist: trusty

matrix:
  include:
  - php: 7.4
    env: ANALYSIS='true'
  - php: 7.4
    env: COMPOSER_ARGS='--prefer-lowest'
  - php: 8.1
  - php: 8.2
  - php: 8.3
  - php: 8.4
  - php: nightly
    env: COMPOSER_ARGS='--ignore-platform-reqs'
  allow_failures:
  - php: nightly

before_script:
- composer update $COMPOSER_ARGS

script:
- mkdir -p build/logs
- php vendor/bin/phpunit -c phpunit.xml.dist
- if [[ "$ANALYSIS" == 'true' ]]; then php vendor/bin/phpcs ; fi

after_success:
- if [[ "$ANALYSIS" == 'true' ]]; then php vendor/bin/coveralls -v -r /home/travis/build/chico-rei/cielo-ecommerce-v3-php/ ; fi
